spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
gientech:
  security:
    jwt:
      effective-time: 43200000
      secret: gientech
    path:
      permit:
        - /user/login
        - /user/register
